name: code-churn

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  churn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run action
        uses: oierxjn/daily-code-churn@latest
        with:
          days: "30"
          out: "daily-churn.svg"
